### ISSUE TITLE
Dashboard to Support Operator Rework

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1475]
The ODH Operator is getting a rework. We are losing access to KfDefs in favour of a CRD. There will be migration involved in no longer handling some resources in the Dashboard and those will be moved to other components. This will be a longer effort to support isolated functionality and not make the Dashboard a dumping ground for support.

Items that need to be investigated by this work and broken down into stories or a simple answer are the following.

- [ ] Is the Dashboard using KfDefs reading?
- [ ] Notebook Sizes & Model Serving Sizes, are they being moved to another repo / CR?
- [ ] Feature Flags are still needed in the Dashboard, but do we lean on the Operator state before showing it in the UI? (aka. feature flag to exclude, not include)
- [ ] How do we deal with feature flags for items that are not component based? (DS Projects for instance)
- [ ] Testing the Operator with the Dashboard code -- how is this done?
- [ ] Can the eventual Dynamic Plugin SDK be incorporated into the Operator's CRD?
- [ ] What are the items the Dashboard would like to have the Operator control? (eg. Replica count)

More questions may be answered as investigation and conversations continue.

**Comment by andrewballantyne** [comment]
We won't complete this for this sprint... we will address the initial issue with Pipelines locking down the Dashboard Project UI (https://github.com/opendatahub-io/odh-dashboard/issues/1870) but not the more improved usage of ignoring feature flags when the component is off (https://github.com/opendatahub-io/odh-dashboard/issues/2010).

**Comment by andrewballantyne** [comment]
Basic support for the Operator has been done and https://github.com/opendatahub-io/odh-dashboard/issues/2010 has been moved to a feature enhancement for next sprint.

We will be closing this tracker as it has completed the basic goal it set out to do which was not crash when using the v2 operator and still offer the same features. 

Due to the nature of the v2 Operator, our feature flags will need to be disabled if the backing component is not there. This will be improved by the 2010 issue noted earlier.
